### ISSUE TITLE
"'pub' is not recognized as [...] command" after successful run

### ISSUE THREAD

**Issue by geisterfurz007** [frencojobs/derry#52]
First of all: Thanks for this! Coming from the JS/TS world, I was happy to see a way to get my beloved script section back :)

Derry works quite well but drops a cheeky "'pub' is not recognized as an internal or external command, operable program or batch file." after succesfully executing all scripts. I don't have pub installed as standalone program and only use it through flutter (as `flutter pub`). This doesn't break anything, it's just "unsettling" to see an error message at the end of a successful command.

I would happily look into this! After a quick glance I couldn't figure out where pub was being executed though, so if you could provide some guidance, that would be amazing!

**Comment by geisterfurz007** [comment]
Hey, sorry for the late reply! This is the scripts section:

```yaml
scripts:
  gen:
    - echo Install packages and dependencies && flutter pub get
    - echo Generating GraphQL files && flutter pub run build_runner build --delete-conflicting-outputs
    - echo Generating l10n files && flutter pub run fast_i18n
```
Dart version: `Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "windows_x64"`  
Flutter version: `Flutter 2.2.3 • channel stable • https://github.com/flutter/flutter.git`  
Derry version: `1.4.1`

Interestingly the error already appears after running `derry --version` and appears to be unrelated to the script that is being executed (sorry for not trying that earlier):

![grafik](https://user-images.githubusercontent.com/26303198/131256249-274fcd9f-72ac-4206-a11f-ad96f22af739.png)
