### ISSUE TITLE
Passing CLI arguments to scripts

### ISSUE THREAD

**Issue by elektronik2k5** [frencojobs/derry#53]
Hello and thanks for creating and maintaining `derry`!

This may seem like a silly question, but I can't seem to be able to pass CLI arguments to scripts. Is that no supported? My use case is running tests of modified files via git hooks. Given this file:

```yaml
flutter:
  - fvm flutter
 
test:
  - $flutter test --no-pub --coverage
```
I want to be able to pass paths of files to run
```bash
derry test lib/file_test.dart lib/some/other_file_test.dart [more files here via shell glob]
```
But I haven't found a way to do that. Did I miss something obvious?
