### ISSUE TITLE
Is it possible to create variables on the yaml file?

### ISSUE THREAD

**Issue by rodrigobastosv** [frencojobs/derry#57]
First of all, congratulations for the great work!

I have repetitive snippets of values ​​that I reuse in several different commands, it would be great if I could create variables with these values ​​to reuse them. 

It is possible?

I didn't find anything related to this in the documentation.

**Comment by sonjz** [comment]
you could use environment variables
```
# your script.yaml in pubspec.yaml
test:
  test1:
    - echo "1 $TEST_VAR"
  test2:
    - echo "2 $TEST_VAR"
```

run with
```
TEST_VAR=something derry test test1
TEST_VAR=something derry test test2
```
