### ISSUE TITLE
control position of additional arguments

### ISSUE THREAD

**Issue by beerline** [frencojobs/derry#63]
Hi! Thank u for such amazing tool!

Some time when i using derry for really complicated scripts it can be useful to control position of additional arguments in running script.

Example:
pubspec.yaml

```
scripts:
  my-command: touch '$1'|echo '$2' > '$1'
```

as result of command: `derry my-command -- my_file_name file_content`
we will get file with `file_name` containing `file_content`

Let me know if i can implement this feature

**Comment by beerline** [comment]
or we can even do a named parameters.

Example:
`pubspec.yaml`

``` yaml
scripts:
# using named parameters 
  my-command: touch '$file_name'|echo '$content' > '$file_name'
# using position parameters
  my-command: touch '$1'|echo '$2' > '$1'
```

Usage:
can be used as named and position parameters 
``` bash
derry my-command -- file_name=my_file_name content=file_content
```

can be used ONLY as position parameters 
``` bash
derry my-command -- my_file_name file_content
```

if position of parameters not specified at `pubspec.yaml` they will add in the end of command keeping the order (as it works right now).
