### ISSUE TITLE
Allow default for nested command

### ISSUE THREAD

**Issue by jibbers42** [frencojobs/derry#67]
Is there a way to allow a default when using nested commands?

```yaml
// syntax seems not allowed in yaml (from IDE message in vscode, not personally sure)
scripts:
  gen: dart run build_runner build
    del: dart run build_runner build --delete-conflicting-outputs

// this syntax is allowed, but can't call the default with derry
// (or even if I knew how, it wouldn't be more convenient than just giving it a name
scripts:
  gen:
    : dart run build_runner build
    del: dart run build_runner build --delete-conflicting-outputs

// maybe some way of making this work?
scripts:
  gen:
    - dart run build_runner build
    - del: dart run build_runner build --delete-conflicting-outputs

// or maybe derry can just reserve the name "default"?
scripts:
  gen:
    default: dart run build_runner build
    del: dart run build_runner build --delete-conflicting-outputs
```

Looking at the second style above, I think if `derry gen` could run the script with no name that would be cool - assuming there are no other issues with this approach.
