### ISSUE TITLE
FEAT: Create alias input for command

### ISSUE THREAD

**Issue by mrgnhnt96** [frencojobs/derry#83]
# Description

As a developer, it's essential to maintain descriptive and explicit scripts for better understanding, especially for new team members. However, dealing with lengthy and explicit terminal commands can become tedious. To address this, there's a need to shorten the commands while preserving clarity.

# Current Workaround

```yaml
build_runner:
   build: flutter packages run build_runner build --delete-conflicting-outputs
   watch: flutter package run build_runner watch --delete-conflicting-outputs

br:
    b: $build_runner:build
    w: $build_runner:watch
```

# Proposal

I propose introducing an 'aliases' feature for each command, providing a more concise representation.

```yaml
build_runner:
   (aliases):
      - br
      - runner
   build:
      (scripts): flutter packages run build_runner build --delete-conflicting-outputs
      (aliases): b
   watch:
      (scripts): flutter package run build_runner watch --delete-conflicting-outputs
      (aliases): w
```

# Alt Proposal

Here is an alternate approach that could be taken. It might make it easier for adoption since this approach is easier to read. However, it might be more difficult to implement as some pattern matching and parsing would be necessary

```yaml
build_runner(br,runner): # multiple aliases are comma separated
   build(b): flutter packages run build_runner build --delete-conflicting-outputs
   watch(w): flutter package run build_runner watch --delete-conflicting-outputs
```
